version: "3"
services:
  web:
    container_name: poc_next
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/usr/src/app/
    ports:
      - "3000:3000"
    networks:
      - poc
  postgres:
    container_name: poc_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - poc

  pgadmin:
    container_name: poc_pgadmin
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - poc

networks:
  poc:
    driver: bridge
